# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'STORM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Alamofire'

  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'CodableFirebase'

  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'

  # Pods for STORM

end
